version: '3'

services:
  backend:
    build: .
    volumes:
      - ./backend:/app/backend
      - /tmp:/tmp
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - LLM_PROVIDER=${LLM_PROVIDER:-openai}
    working_dir: /app
    command: ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: unless-stopped

  frontend:
    image: node:20
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    working_dir: /app
    command: bash -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      - backend
    restart: unless-stopped