services:
  - type: web
    name: webcad-backend
    env: docker
    repo: https://github.com/amywork777/webappacad
    branch: main
    dockerfilePath: Dockerfile
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 8080
    region: oregon
    plan: standard
    healthCheckPath: /
    port: 8080
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: LLM_PROVIDER
        value: openai